MAX_VEHICLES_ON_PAGE = 5

GAME_VEHICLES = [
    {
        'id': 401,
        'brand': 'audi',
        'model_name': 'a8',
        'price': 340_000,
        'autosalon_preview_image_url': '/assets/images/autosalon_previews/audi/a8.jpg', # plus 'process.env.PUBLIC_URL' folder-path on Front-End part of project
        'description': 'Сочетает в себе высокую производительность, элегантный дизайн и передовые технологии.',
        'specifications': {
            'maxspeed': 200,
            'acceleration': 14,
            'control': 6,
        },
    },
    {
        'id': 402,
        'brand': 'audi',
        'model_name': 'r8',
        'price': 12_000_000,
        'autosalon_preview_image_url': '/assets/images/autosalon_previews/audi/r8.jpg',
        'description': 'Спортивный автомобиль, который отличается высокой скоростью, мощностью и элегантным дизайном.',
        'specifications': {
            'maxspeed': 200,
            'acceleration': 14,
            'control': 6,
        },
    },
    {
        'id': 403,
        'brand': 'audi',
        'model_name': 'rs6',
        'price': 6_500_000,
        'autosalon_preview_image_url': '/assets/images/autosalon_previews/audi/rs6.jpg',
        'description': 'Высокопроизводительный универсал, который сочетает в себе мощный двигатель, спортивный дизайн и отличную управляемость.',
        'specifications': {
            'maxspeed': 200,
            'acceleration': 14,
            'control': 6,
        },
    },
    {
        'id': 404,
        'brand': 'audi',
        'model_name': 'rs7',
        'price': 7_250_000,
        'autosalon_preview_image_url': '/assets/images/autosalon_previews/audi/rs7.jpg',
        'description': 'Cпортивный седан, который отличается высокой скоростью, мощностью и элегантным дизайном.',
        'specifications': {
            'maxspeed': 200,
            'acceleration': 14,
            'control': 6,
        },
    },
    {
        'id': 405,
        'brand': 'audi',
        'model_name': 's5',
        'price': 7_250_000,
        'autosalon_preview_image_url': '/assets/images/autosalon_previews/audi/s5.jpg',
        'description': 'Динамика, управляемость, скорость. Идеальный выбор для любителей быстрой езды.',
        'specifications': {
            'maxspeed': 200,
            'acceleration': 14,
            'control': 6,
        },
    },
    {
        'id': 406,
        'brand': 'bentley',
        'model_name': 'bentayga',
        'price': 16_500_000,
        'autosalon_preview_image_url': '/assets/images/autosalon_previews/bentley/bentayga.jpg',
        'description': 'Динамика, управляемость, скорость. Идеальный выбор для любителей быстрой езды.',
        'specifications': {
            'maxspeed': 240,
            'acceleration': 6,
            'control': 7,
        },
    },
    {
        'id': 407,
        'brand': 'bentley',
        'model_name': 'continental',
        'price': 7_000_000,
        'autosalon_preview_image_url': '/assets/images/autosalon_previews/bentley/continental.jpg',
        'description': 'Динамика, управляемость, скорость. Идеальный выбор для любителей быстрой езды.',
        'specifications': {
            'maxspeed': 240,
            'acceleration': 6,
            'control': 7,
        },
    },
    {
        'id': 407,
        'brand': 'bentley',
        'model_name': 'continental',
        'price': 7_000_000,
        'autosalon_preview_image_url': '/assets/images/autosalon_previews/bentley/continental.jpg',
        'description': 'Динамика, управляемость, скорость. Идеальный выбор для любителей быстрой езды.',
        'specifications': {
            'maxspeed': 240,
            'acceleration': 6,
            'control': 7,
        },
    },
    {
        'id': 407,
        'brand': 'bentley',
        'model_name': 'continental',
        'price': 7_000_000,
        'autosalon_preview_image_url': '/assets/images/autosalon_previews/bentley/continental.jpg',
        'description': 'Динамика, управляемость, скорость. Идеальный выбор для любителей быстрой езды.',
        'specifications': {
            'maxspeed': 240,
            'acceleration': 6,
            'control': 7,
        },
    },
    {
        'id': 407,
        'brand': 'bentley',
        'model_name': 'continental',
        'price': 7_000_000,
        'autosalon_preview_image_url': '/assets/images/autosalon_previews/bentley/continental.jpg',
        'description': 'Динамика, управляемость, скорость. Идеальный выбор для любителей быстрой езды.',
        'specifications': {
            'maxspeed': 240,
            'acceleration': 6,
            'control': 7,
        },
    },
    {
        'id': 407,
        'brand': 'bentley',
        'model_name': 'continental',
        'price': 7_000_000,
        'autosalon_preview_image_url': '/assets/images/autosalon_previews/bentley/continental.jpg',
        'description': 'Динамика, управляемость, скорость. Идеальный выбор для любителей быстрой езды.',
        'specifications': {
            'maxspeed': 240,
            'acceleration': 6,
            'control': 7,
        },
    },
]